sonar.projectKey=fastapi-demo
sonar.projectName=fastapi-demo
sonar.organization=pjain047
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**
sonar.python.coverage.reportPaths=coverage.xml