apiVersion: v1
kind: Secret
metadata:
  name: fastapi-demo-secret
  namespace: fastapi-demo
  labels:
    app: fastapi-demo

type: Opaque

data:
  DEMO_USERNAME: cGphbmFsaW4=
  DEMO_API_KEY: cGFzc3dvcmQxMjM=