apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
  namespace: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  type: NodePort
  selector:
    app: fastapi-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
