grafana:
  enabled: true

  service:
    type: ClusterIP

prometheus:
  enabled: true
  serviceMonitorSelectorNilUsesHelmValues: false
  serviceMonitoringNamspaceSeletor: {}
  serviceMonitoringSelector: {}

  service:
    type: ClusterIP

  prometheusSpec:
    retention: 2d

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
